---
- name: Installer Apache (Debian/Ubuntu)
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installer Apache (RedHat/CentOS)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Déployer la page d'accueil personnalisée
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

 #- name: Démarrer et activer Apache
 # service:
 #   name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
 #   state: started
 #   enabled: yes
