---
- name: Mettre à jour la liste des paquets
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Mettre à jour tous les paquets
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Supprimer les paquets inutiles
  apt:
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == "Debian"

